# SPDX-License-Identifier: EUPL-1.2
#
# (C) Copyright 2018-2024 CSI-Piemonte

uwsgi:
    api_id: auth-01
    api_name: beehive
    api_subsystem: auth
    api_package: beehive
    api_env: beehive200
    api_fernet_key: xxxkey
    api_host: localhost
    api_fqdn: localhost
    api_catalog: beehive-internal
    api_endpoint: http://localhost:8070
    api_timeout: 60
    api_log: /tmp/
    api_swagger_spec_path: %d../swagger.yml
    #api_logging_level: -10
    api_logging_level: 10

    # task manager / scheduler
    broker_url: redis://localhost:6379/0
    broker_queue: celery.auth
    result_backend: redis://localhost:6379/0
    expire: 86400
    task_time_limit: 1200

    # socket configuration uwsi,http
    socket: :8070
    http-socket: :8080

    # startup user
    #uid: uwsgi
    #gid: uwsgi

    # daemon configuration
    daemonize: /tmp/auth-01.api.out
    pidfile: /tmp/auth-01.pid
    vacuum: true

    # python configuration
    virtualenv: %d../../
    py-programname: python

    # process configuration
    master: true
    enable-threads: true
    workers: 2
    gevent: 200
    gevent-monkey-patch: true
    procname: auth-01
    cpu-affinity: 1

    # queue configuration
    #queue: 10
    #queue-blocksize: 64000

    #cache2: name=portal_cache,items=100

    # app configuration
    module: beehive.server.api:app

    oauth2_endpoint: ''

    # database uri
    database_uri: mysql+pymysql://auth:auth@localhost:3306/auth

    # redis uri
    redis_identity_uri: redis://localhost:6379/0
    redis_queue_uri: redis://localhost:6379/0
    redis_celery_uri: redis://localhost:6379/0

    # elasticsearch nodes
    elasticsearch_nodes: ''

    # task modules
    task_module: 3
    task_module.1: beehive.module.scheduler_v2.tasks
    task_module.2: beehive.module.auth.tasks_v2
    task_module.3: beehive.module.catalog.tasks_v2

    # api modules
    api_module: 4
    api_module.1: beehive.module.basic.mod.BasicModule
    api_module.2: beehive.module.auth.mod.AuthModule,true
    api_module.3: beehive.module.catalog.mod.CatalogModule
    api_module.4: beehive.module.scheduler_v2.mod.SchedulerModuleV2

    # api plugins
    # api_plugin: 0

    # event handler
    # event_handler: 0

    # workers configuration
    attach-daemon2: cmd=%(virtualenv)bin/pyenv.sh %(virtualenv) task.py %p 2>&1 >/tmp/auth-01.worker.out,stopsignal=2,reloadsignal=1
    attach-daemon2: cmd=%(virtualenv)bin/pyenv.sh %(virtualenv) scheduler.py %p 2>&1 >/tmp/auth-01.scheduler.out,stopsignal=2,reloadsignal=1
    attach-daemon2: cmd=%(virtualenv)bin/pyenv.sh %(virtualenv) catalog.py %p 2>&1 >/tmp/auth-01.catalog.out,stopsignal=2,reloadsignal=1
