# SPDX-License-Identifier: EUPL-1.2
#
# (C) Copyright 2018-2024 CSI-Piemonte

---
schema: resource
db-uris:
  auth:
  event:
  ssh:
  resource:
  service:
redis:
  uri_complete: redis://:ppp@<MINIKUBE_IP>:31281/0
  uri: <MINIKUBE_IP>;<REDIS_SERVICE_PORT>;0
  cluster:
worker:
  result: redis://<MINIKUBE_IP>:<REDIS_SERVICE_PORT>/0
  broker: redis://<MINIKUBE_IP>:<REDIS_SERVICE_PORT>/0
  #result: redis://localhost:6379/0
  #broker: redis://localhost:6379/0
  queue: celery.auth
endpoints:
  auth: https://<HOST_NGINX>:443/mylab
  event: https://<HOST_NGINX>:443/mylab
  ssh: https://<HOST_NGINX>:443/mylab
swagger:
  auth: http://<MINIKUBE_IP>:30000/apispec_1.json
  event: http://<MINIKUBE_IP>:30001/apispec_1.json
  ssh: http://<MINIKUBE_IP>:30001/apispec_1.json
users:
 admin:
   user: admin@local
   pwd: beehive_admin
   secret:
   ip: localhost
   auth: keyauth
   catalog: beehive-internal
 test1:
   user: name1@local
   pwd: xxxxxxxxx
   secret:
   ip: 192.168.49.111
   auth: keyauth
   catalog: beehive-internal
