swagger: "2.0"
info:
  title: Beehive API
  description: API description in Markdown.
  contact:
    email: me@csi.it
    url: http://www.me.com
  license:
    name: MIT
    url: https://github.com/swagger-api/swagger-ui/blob/master/LICENSE    
  termsOfService: http://me.com/terms
  version: 1.0.0
host: tst-beehive
schemes: 
  - http
  - https
tags:
  - name: base
    description: base api
  - name: authorization
    description: authorization api
  - name: keyauth
    description: public/private key authorization api     
  - name: oauth2
    description: oauth2 authorization api    
  - name: directory
    description: directory api
  - name: event
    description: event api
  - name: scheduler
    description: scheduler and task manager api
  - name: resource
    description: resource base api
  - name: openstack
    description: resource plugin opensatck api
  - name: vsphere
    description: resource plugin vsphere api
  - name: provider
    description: resource plugin provider api
  - name: organization
    description: service api - organization
  - name: division
    description: service api - division
  - name: account
    description: service api - account
  - name: servicetype
    description: service api - servicetype
  - name: serviceinstance
    description: service api - serviceinstance 
consumes:
  - application/json
  - application/xml
produces:
  - application/json
  - application/xml
  - text/plain
securityDefinitions:
  BasicAuth:
    type: basic
  ApiKeyAuth:
    type: apiKey
    in: header
    name: uid
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://<hostname>/v1.0/oauth2/authorize/
    tokenUrl: https://<hostname>/v1.0/oauth2/token/
    scopes:
      auth: authorization scope
      beehive: beehive ecosystem
# Descriptions of common responses
responses:
  DefaultError:
    description: Defualt error syntax
    schema:
      $ref: "#/definitions/Error" 
  InternalServerError:
    description: The operation failed. An unexpected exception occurred while 
                 executing the operation. The response-body contains details 
                 about the error.               
  BadRequest:
    description: The specified resource was not found. Syntax like default.      
  NotFound:
    description: The operation failed.The requested resource was not found.
                  Syntax like default.    
  Unauthorized:
    description: The operation failed. The operation requires an 
                 Authentication header to be set. If this was present 
                 in the request, the supplied credentials are not valid 
                 or the user is not authorized to perform this operation.
                  Syntax like default.              
  Forbidden:
    description: The operation is forbidden and should not be re-attempted. This 
                 does not imply an issue with authentication not authorization, 
                 it is an operation that is not allowed. Example. deleting a 
                 task that is part of a running process is not allowed and will 
                 never be allowed, regardless of the user or process/task state.
                  Syntax like default.               
  MethodAotAllowed:
    description: The operation failed. The used method is not allowed for this 
                 resource. E.g. trying to update (PUT) a deployment-resource 
                 will result in a 405 status.
                  Syntax like default.                   
  NotAcceptable:
    description: Not acceptable. Syntax like default.      
  Timeout:
    description: Operation timeout. Syntax like default.
  Conflict:
    description: The operation failed. The operation causes an update of a 
                 resource that has been updated by another operation, which 
                 makes the update no longer valid. Can also indicate a resource 
                 that is being created in a collection where a resource with 
                 that identifier already exists.
                  Syntax like default.
  UnsupportedMediaType:
    description: The operation failed. The request body contains an unsupported 
                 media type. Also occurs when the request-body JSON contains an 
                 unknown attribute or value that doesn’t have the right 
                 format/type to be accepted.
                  Syntax like default.
  Gone:
    description: Indicates that the resource at this end point is no longer available.
                  Syntax like default.
  UnprocessableEntity:
    description: The request was well-formed but was unable to be followed due 
                 to semantic errors. Syntax like default.
  TooManyRequests:
    description: The user has sent too many requests in a given amount of time.
                  Syntax like default.
definitions:
  # Schema for error response body
  Error:
    type: object
    required: [code, message, description]
    properties:
      code:
        type: integer
        example: "<http error code>"
      message:
        type: string
        example: Some error
      description:
        type: string
        example: Some error description
                   